export const GameConfig = {
  STARTING_HEALTH: 10,
  STARTING_TURRET_STRENGTH: 1,
  STARTING_AREA_ATTACK_RADIUS: 80,
  STARTING_AREA_ATTACK_POWER: 1,
  STARTING_CAMERA_SPEED: 300,
  STARTING_SCORE: 0,
  STARTING_LEVEL: 0,

  MAX_LASER_AMMO: 35,
  MAX_EXPLOSIVE_AMMO: 40,
  MAX_MELEE_AMMO: 5,
  AMMO_REGEN_INTERVAL_MS: 100,
  AMMO_REGEN_DELAY_AFTER_SHOOT_MS: 3000,
  AMMO_REGEN_PER_TICK: 1,

  STARTING_ENEMY_HEALTH: 3,
  ENEMY_BASE_SPEED: 285,

  ENEMY_SPAWN_DELAY_MS: 1500,

  LASER_SPEED: 450,
  ROCKET_SPEED: 320,

  EXPLOSION_RADIUS: 140,
  CHAIN_RADIUS: 220,
  CHAIN_DAMAGE: 0.5,

  MELEE_DAMAGE: 3,
  MELEE_RANGE: 150,
  MELEE_COOLDOWN_MS: 800,

  SCORE_PER_KILL: 10,
  // Increase threshold so quiz popups are less frequent (now every 150 points)
  SCORE_PER_LEVEL: 150,

  DEFAULT_FPS: 60,
} as const;
