export const GameConfig = {
  STARTING_HEALTH: 10,
  STARTING_TURRET_STRENGTH: 1,
  STARTING_AREA_ATTACK_RADIUS: 80,
  STARTING_AREA_ATTACK_POWER: 1,
  STARTING_CAMERA_SPEED: 300,
  STARTING_SCORE: 0,
  STARTING_LEVEL: 0,

  MAX_LASER_AMMO: 35,
  MAX_EXPLOSIVE_AMMO: 40,
  MAX_MELEE_AMMO: 5,
  AMMO_REGEN_INTERVAL_MS: 100,
  AMMO_REGEN_DELAY_AFTER_SHOOT_MS: 3000,
  AMMO_REGEN_PER_TICK: 1,

  STARTING_ENEMY_HEALTH: 3,
  ENEMY_BASE_SPEED: 285,

  ENEMY_SPAWN_DELAY_MS: 1500,

  LASER_SPEED: 450,
  ROCKET_SPEED: 320,

  EXPLOSION_RADIUS: 140,
  CHAIN_RADIUS: 220,
  CHAIN_DAMAGE: 0.5,

  EXPLOSION_CENTER_MULTIPLIER: 0.4,
  EXPLOSION_SOFTEN: 0.2,

  SPAWN_SCALE_PER_LEVEL: 0.85,
  MIN_SPAWN_DELAY_MS: 200,

  MELEE_DAMAGE: 3,
  MELEE_RANGE: 150,
  MELEE_COOLDOWN_MS: 800,

  SCORE_PER_KILL: 10,
  SCORE_PER_LEVEL: 150,

  DEFAULT_FPS: 60,
  LASER_HIT_COOLDOWN_MS: 150,
  LASER_LIFETIME_MS: 2000,

  AMMO_BOOST_LASER: 5,
  AMMO_BOOST_EXPLOSIVE: 7,
  AMMO_BOOST_MELEE: 1,
} as const;
